export interface Song {
  id: number
  title: string
  artist: string
  genre: string
  category: string
  duration: number
  youtubeUrl: string
  lyrics?: string
  syncedLyrics?: Array<{ time: number; text: string }>
}

const extractYouTubeId = (url: string) => {
  const match = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&?/]+)/)
  return match ? match[1] : ""
}

export const allSongs: Song[] = [
  // Congolese Music
  {
    id: 1,
    title: "Tokoos",
    artist: "Fally Ipupa",
    genre: "Congolese",
    category: "Congolese",
    duration: 264,
    youtubeUrl: "https://youtu.be/Zl5WWdNJT0U",
    lyrics: "Tokoos, tokoos...\n(Lyrics available on YouTube)",
    syncedLyrics: [
      { time: 0, text: "♪ Tokoos ♪" },
      { time: 10, text: "Fally Ipupa" },
      { time: 20, text: "Tokoos, tokoos..." },
      { time: 30, text: "Mon amour, tu es ma vie" },
      { time: 45, text: "Je t'aime, je t'aime" },
      { time: 60, text: "Tokoos baby" },
    ],
  },
  {
    id: 2,
    title: "Eau Benite",
    artist: "Fally Ipupa",
    genre: "Congolese",
    category: "Congolese",
    duration: 298,
    youtubeUrl: "https://youtu.be/TMyXZrWzgGQ?list=RDTMyXZrWzgGQ",
    lyrics: "Mon amour, tu es mon eau bénite...\n(Full lyrics available on YouTube)",
  },
  {
    id: 3,
    title: "Sweet Fanta Diallo",
    artist: "Fally Ipupa",
    genre: "Congolese",
    category: "Congolese",
    duration: 276,
    youtubeUrl: "https://youtu.be/wv15GiQ4sVg?list=RDwv15GiQ4sVg",
    lyrics: "Sweet Fanta Diallo...\nMon coeur bat pour toi",
  },
  {
    id: 4,
    title: "Loi",
    artist: "Fally Ipupa",
    genre: "Congolese",
    category: "Congolese",
    duration: 321,
    youtubeUrl: "https://youtu.be/ETzJwQlXTsE?list=RDETzJwQlXTsE",
    lyrics: "C'est la loi de l'amour...",
  },
  {
    id: 5,
    title: "Show Me the Way",
    artist: "Fally Ipupa",
    genre: "Congolese",
    category: "Congolese",
    duration: 254,
    youtubeUrl: "https://youtu.be/9wYLK6ek4Y0?list=RD9wYLK6ek4Y0",
    lyrics: "Show me the way to your heart...",
  },
  {
    id: 6,
    title: "Unknown Track 1",
    artist: "Congolese Artist",
    genre: "Congolese",
    category: "Congolese",
    duration: 240,
    youtubeUrl: "https://youtu.be/ZcM82ZTy-1o?list=RDZcM82ZTy-1o",
  },
  {
    id: 7,
    title: "Unknown Track 2",
    artist: "Congolese Artist",
    genre: "Congolese",
    category: "Congolese",
    duration: 235,
    youtubeUrl: "https://youtu.be/1ajf7E6wHuA?list=RD1ajf7E6wHuA",
  },
  {
    id: 8,
    title: "Unknown Track 3",
    artist: "Congolese Artist",
    genre: "Congolese",
    category: "Congolese",
    duration: 245,
    youtubeUrl: "https://youtu.be/6eRBaoG1cTI?list=RD6eRBaoG1cTI",
  },
  {
    id: 9,
    title: "Unknown Track 4",
    artist: "Congolese Artist",
    genre: "Congolese",
    category: "Congolese",
    duration: 250,
    youtubeUrl: "https://youtu.be/QemzwQ839tE?list=RDQemzwQ839tE",
  },
  {
    id: 10,
    title: "Unknown Track 5",
    artist: "Congolese Artist",
    genre: "Congolese",
    category: "Congolese",
    duration: 260,
    youtubeUrl: "https://youtu.be/aBNwqZoV1kU?list=RDaBNwqZoV1kU",
  },
  {
    id: 11,
    title: "Unknown Track 6",
    artist: "Congolese Artist",
    genre: "Congolese",
    category: "Congolese",
    duration: 255,
    youtubeUrl: "https://youtu.be/Ylh6IXnQMFg?list=RDYlh6IXnQMFg",
  },
  // Brenda Fassie
  {
    id: 12,
    title: "Vutha",
    artist: "Brenda Fassie",
    genre: "Afropop",
    category: "African",
    duration: 270,
    youtubeUrl: "https://youtu.be/JB-OGtSEc64?list=RDJB-OGtSEc64",
    lyrics: "Vutha, vutha...\nThe queen of African pop!",
  },
  // K-pop
  {
    id: 13,
    title: "Not Cute Anymore",
    artist: "K-pop Artist",
    genre: "K-pop",
    category: "K-pop",
    duration: 195,
    youtubeUrl: "https://youtu.be/x_RYZsOfpKY?list=RDx_RYZsOfpKY",
  },
  {
    id: 14,
    title: "Gabriela",
    artist: "K-pop Artist",
    genre: "K-pop",
    category: "K-pop",
    duration: 205,
    youtubeUrl: "https://youtu.be/co-TFLbaZAE?list=RDco-TFLbaZAE",
  },
  {
    id: 15,
    title: "Internet Girl",
    artist: "K-pop Artist",
    genre: "K-pop",
    category: "K-pop",
    duration: 200,
    youtubeUrl: "https://youtu.be/t9xvL75oU6w?list=RDt9xvL75oU6w",
  },
  {
    id: 16,
    title: "Tonight I Might",
    artist: "Katseye",
    genre: "K-pop",
    category: "K-pop",
    duration: 185,
    youtubeUrl: "https://youtu.be/bkCzR4uKOeg?list=RDbkCzR4uKOeg",
  },
  {
    id: 17,
    title: "Moonstruck",
    artist: "Enhypen",
    genre: "K-pop",
    category: "K-pop",
    duration: 210,
    youtubeUrl: "https://youtu.be/InC7wcQK25Y?list=RDInC7wcQK25Y",
    lyrics: "I'm moonstruck by you...\nCan't escape this feeling",
    syncedLyrics: [
      { time: 0, text: "♪ Moonstruck ♪" },
      { time: 8, text: "I'm moonstruck by you" },
      { time: 15, text: "Can't escape this feeling" },
      { time: 23, text: "Lost in your eyes tonight" },
      { time: 30, text: "You got me hypnotized" },
      { time: 40, text: "Like the moon in the sky" },
      { time: 50, text: "I'm falling, falling for you" },
    ],
  },
  {
    id: 18,
    title: "Polaroid Love",
    artist: "Enhypen",
    genre: "K-pop",
    category: "K-pop",
    duration: 178,
    youtubeUrl: "https://youtu.be/NU5mFeTcJSo?list=RDNU5mFeTcJSo",
    lyrics: "It's like a polaroid love\nLove that old feeling",
    syncedLyrics: [
      { time: 0, text: "♪ Polaroid Love ♪" },
      { time: 5, text: "It's like a polaroid love" },
      { time: 12, text: "Love that old feeling" },
      { time: 20, text: "Staying close beside you" },
      { time: 28, text: "That sweet scent of yours" },
      { time: 35, text: "Polaroid of you and me" },
      { time: 45, text: "Together forever" },
    ],
  },
  {
    id: 19,
    title: "My Way",
    artist: "Katseye",
    genre: "K-pop",
    category: "K-pop",
    duration: 192,
    youtubeUrl: "https://youtu.be/JB-OGtSEc64?list=RDJB-OGtSEc64",
  },
  {
    id: 20,
    title: "Take What You Want",
    artist: "Cortis",
    genre: "K-pop",
    category: "K-pop",
    duration: 215,
    youtubeUrl: "https://youtu.be/OeO081S4Gt0?list=RDOeO081S4Gt0",
  },
  {
    id: 21,
    title: "Take My Half",
    artist: "Beomgyu",
    genre: "K-pop",
    category: "K-pop",
    duration: 198,
    youtubeUrl: "https://youtu.be/AluSsiJOPiM?list=RDAluSsiJOPiM",
  },
  {
    id: 22,
    title: "Ghost Girl",
    artist: "Yeonjun",
    genre: "K-pop",
    category: "K-pop",
    duration: 202,
    youtubeUrl: "https://youtu.be/RfuWLmuyniE?list=RDRfuWLmuyniE",
  },
  {
    id: 23,
    title: "Sunday Drive",
    artist: "Soobin",
    genre: "K-pop",
    category: "K-pop",
    duration: 188,
    youtubeUrl: "https://youtu.be/MBYKXj4Nscc?list=RDMBYKXj4Nscc",
  },
  // Pop
  {
    id: 24,
    title: "Ocean Eyes",
    artist: "Billie Eilish",
    genre: "Pop",
    category: "Pop",
    duration: 200,
    youtubeUrl: "https://youtu.be/_K582Qm9o08?list=RD_K582Qm9o08",
    lyrics:
      "I've been watching you for some time\nCan't stop staring at those ocean eyes\nBurning cities and napalm skies",
    syncedLyrics: [
      { time: 0, text: "♪ Ocean Eyes ♪" },
      { time: 12, text: "I've been watching you" },
      { time: 18, text: "For some time" },
      { time: 24, text: "Can't stop staring" },
      { time: 30, text: "At those ocean eyes" },
      { time: 40, text: "Burning cities and napalm skies" },
      { time: 50, text: "Fifteen flares inside those ocean eyes" },
      { time: 60, text: "Your ocean eyes" },
    ],
  },
  {
    id: 25,
    title: "Lovely",
    artist: "Billie Eilish",
    genre: "Pop",
    category: "Pop",
    duration: 200,
    youtubeUrl: "https://youtu.be/8VLXHyHRXjc?list=RD8VLXHyHRXjc",
    lyrics: "Isn't it lovely, all alone?\nHeart made of glass, my mind of stone",
    syncedLyrics: [
      { time: 0, text: "♪ Lovely ♪" },
      { time: 15, text: "Thought I found a way" },
      { time: 22, text: "Thought I found a way out" },
      { time: 30, text: "But you never go away" },
      { time: 40, text: "So I guess I gotta stay now" },
      { time: 50, text: "Oh, I hope some day" },
      { time: 58, text: "I'll make it out of here" },
      { time: 68, text: "Even if it takes all night" },
      { time: 76, text: "Or a hundred years" },
    ],
  },
  {
    id: 26,
    title: "Drivers License",
    artist: "Olivia Rodrigo",
    genre: "Pop",
    category: "Pop",
    duration: 242,
    youtubeUrl: "https://youtu.be/ZYpwyJAAuEY?list=RDZYpwyJAAuEY",
    lyrics: "I got my driver's license last week\nJust like we always talked about",
    syncedLyrics: [
      { time: 0, text: "♪ Drivers License ♪" },
      { time: 8, text: "I got my driver's license last week" },
      { time: 16, text: "Just like we always talked about" },
      { time: 24, text: "'Cause you were so excited for me" },
      { time: 32, text: "To finally drive up to your house" },
      { time: 40, text: "But today I drove through the suburbs" },
      { time: 48, text: "Crying 'cause you weren't around" },
    ],
  },
  {
    id: 27,
    title: "Confess Your Love",
    artist: "Pop Artist",
    genre: "Pop",
    category: "Pop",
    duration: 210,
    youtubeUrl: "https://youtu.be/vlJRucQN7F8?list=RDvlJRucQN7F8",
  },
  {
    id: 28,
    title: "Spongebob",
    artist: "Pop Artist",
    genre: "Pop",
    category: "Pop",
    duration: 195,
    youtubeUrl: "https://youtu.be/He-LBIyBUz8",
  },
  {
    id: 29,
    title: "Monster High",
    artist: "Pop Artist",
    genre: "Pop",
    category: "Pop",
    duration: 205,
    youtubeUrl: "https://youtu.be/HLih_hMPoCI?list=RDHLih_hMPoCI",
  },
  {
    id: 30,
    title: "Toxic Till the End",
    artist: "Pop Artist",
    genre: "Pop",
    category: "Pop",
    duration: 218,
    youtubeUrl: "https://youtu.be/xbvezW17yl8?list=RDxbvezW17yl8",
  },
  {
    id: 31,
    title: "Elphaba and Glinda",
    artist: "Wicked Cast",
    genre: "Pop",
    category: "Pop",
    duration: 225,
    youtubeUrl: "https://youtu.be/3-kC0IYJtTs?list=RD3-kC0IYJtTs",
    lyrics: "Because I knew you\nI have been changed for good",
    syncedLyrics: [
      { time: 0, text: "♪ For Good ♪" },
      { time: 15, text: "I've heard it said" },
      { time: 22, text: "That people come into our lives" },
      { time: 30, text: "For a reason" },
      { time: 38, text: "Bringing something we must learn" },
      { time: 50, text: "And we are led to those" },
      { time: 58, text: "Who help us most to grow" },
      { time: 68, text: "If we let them" },
      { time: 76, text: "And we help them in return" },
      { time: 88, text: "Because I knew you" },
      { time: 96, text: "I have been changed for good" },
    ],
  },
  {
    id: 32,
    title: "Mean Girls",
    artist: "Katseye",
    genre: "Pop",
    category: "Pop",
    duration: 190,
    youtubeUrl: "https://youtu.be/MGcPpYhuq-8?list=RDMGcPpYhuq-8",
  },
  {
    id: 33,
    title: "Bloodline",
    artist: "Ariana Grande",
    genre: "Pop",
    category: "Pop",
    duration: 216,
    youtubeUrl: "https://youtu.be/C2sYLRHqXHY?list=RDC2sYLRHqXHY",
    lyrics: "I ain't got no business catching feelings\nI ain't got no business, here I go",
    syncedLyrics: [
      { time: 0, text: "♪ Bloodline ♪" },
      { time: 10, text: "I ain't got no business" },
      { time: 16, text: "Catching feelings" },
      { time: 22, text: "I ain't got no business" },
      { time: 28, text: "Here I go" },
      { time: 35, text: "You give me butterflies" },
      { time: 43, text: "You know I can't deny" },
      { time: 50, text: "But I just like to have a good time" },
    ],
  },
  {
    id: 34,
    title: "New Song",
    artist: "Unknown Artist",
    genre: "Pop",
    category: "Pop",
    duration: 210,
    youtubeUrl: "https://youtu.be/4H7ZJQPPThY?list=RD4H7ZJQPPThY",
    lyrics: "Lyrics not available yet",
  },
]

export { extractYouTubeId }
